name: 🔐 Observability Microservice - CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Destino do deploy'
        required: false
        default: 'production'
        type: choice
        options: [staging, production]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SERVICE_NAME: observability
  TZ: America/Sao_Paulo

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'production' }}
  cancel-in-progress: false

jobs:
  test-runner:
    runs-on: [self-hosted, observability-service]
    name: 🧪 Test Self-hosted Runner
    steps:
      - uses: actions/checkout@v4
      - name: "Guard: forbid r2dbc:h2 outside tests"
        run: |
          set -euo pipefail
          FOUND=$(grep -R --line-number --include='*.yml' --include='*.properties' --include='*.yaml' "r2dbc:h2" src || true)
          if echo "$FOUND" | grep -v "src/test/" | grep -q "r2dbc:h2"; then
            echo "Forbidden r2dbc:h2 reference outside src/test" >&2
            echo "$FOUND" | grep -v "src/test/" >&2 || true
            exit 1
          fi
      - name: Test runner connectivity
        run: |
          echo "🎉 Self-hosted runner está funcionando!"
          echo "🏃 Runner: $(hostname)"
          echo "📅 Data: $(date)"
          echo "👤 Usuário: $(whoami)"
          echo "📁 Diretório: $(pwd)"
          echo "🔍 Java version:"
          java -version || echo "Java não encontrado"
          echo "🐳 Docker version:"
          docker --version || echo "Docker não encontrado"

  build-and-test:
    needs: test-runner
    runs-on: self-hosted
    name: 🏗️ Build and Test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
      - name: Verify Maven wrapper
        run: |
          chmod +x ./mvnw
          ./mvnw --version
      # DESABILITADO: Testes devido incompatibilidade Java 24 com Mockito
      # - name: Run unit tests with coverage
      #   run: ./mvnw clean verify -Dspring.profiles.active=test
      # DESABILITADO: JaCoCo devido incompatibilidade Java 24 com Mockito  
      # - name: Upload JaCoCo coverage reports
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: jacoco-coverage-reports
      #     path: |
      #       target/site/jacoco/
      #       target/site/jacoco/jacoco.xml
      #     retention-days: 30
      # TEMPORARIAMENTE DESABILITADO: Snyk SAST com problema de JAVA_HOME em container Docker
      # TODO: Reabilitar após correção do ambiente Java no container Snyk
      # - name: Run Snyk SAST security scan
      #   uses: snyk/actions/maven@master
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     args: |
      #       --all-projects 
      #       --severity-threshold=high 
      #       --fail-on=all 
      #       --project-name=observability-service
      # - name: Monitor with Snyk (main branch only)
      #   if: github.ref == 'refs/heads/main'
      #   uses: snyk/actions/maven@master
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     command: monitor
      #     args: --project-name=observability-service
      - name: Build application (skip tests)
        run: ./mvnw clean package -DskipTests
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: observability-microservice-jar
          path: target/*.jar
          retention-days: 7

  build-image:
    runs-on: self-hosted
    name: 🐳 Build Docker Image
    needs: build-and-test
    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
      image-name-lower: ${{ steps.image_name.outputs.image_name_lower }}
      image-tags: ${{ steps.meta.outputs.tags }}
    steps:
      - uses: actions/checkout@v4
      - name: Compute lowercase image name
        id: image_name
        run: |
          set -euo pipefail
          REPO='${{ env.IMAGE_NAME }}'
          echo "image_name_lower=$(echo "$REPO" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.image_name.outputs.image_name_lower }}
          tags: |
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{date 'YYYY-MM-DD-HHmmss'}}-{{sha}},enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=Observability Microservice
            org.opencontainers.image.description=Observability and Metrics Microservice
            org.opencontainers.image.service=${{ env.SERVICE_NAME }}
      - name: Build and push image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          sbom: true
          provenance: mode=max
          cache-from: type=gha
          cache-to: type=gha,mode=max
          network: host
          build-args: |
            SERVICE_NAME=${{ env.SERVICE_NAME }}
            BUILD_DATE=${{ github.event.head_commit.timestamp || github.run_id }}
            VCS_REF=${{ github.sha }}
            VERSION=1.0.0

  sign-image:
    runs-on: self-hosted
    name: ✍️ Sign & Verify (100% OIDC keyless)
    needs: build-image
    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write
    steps:
      - name: Verify OIDC token availability
        run: |
          echo "🔍 Verifying OIDC token is available..."
          if [ -z "${ACTIONS_ID_TOKEN_REQUEST_TOKEN:-}" ]; then
            echo "❌ OIDC token not available"
            exit 1
          fi
          echo "✅ OIDC token is available"
      - name: Resolve image digest ref
        id: ref
        run: |
          set -euo pipefail
          IMG="ghcr.io/${{ needs.build-image.outputs.image-name-lower }}@${{ needs.build-image.outputs.image-digest }}"
          echo "lower=$(echo "$IMG" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
      - name: Install cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: v2.5.3
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull digest
        run: docker pull "${{ steps.ref.outputs.lower }}"
      - name: Sign (keyless OIDC)
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          echo "🔐 Signing container image with OIDC keyless signature..."
          cosign sign --yes "${{ steps.ref.outputs.lower }}"
      - name: Verify OIDC signature
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          echo "✅ Verifying OIDC keyless signature..."
          cosign verify \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            --certificate-identity-regexp "^https://github.com/${{ github.repository }}/\.github/workflows/.*@refs/heads/main$" \
            "${{ steps.ref.outputs.lower }}"
          echo "🎉 Container image signature verified successfully!"

  deploy-production:
    needs: [build-image, sign-image]
    runs-on: [self-hosted, observability-service]
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.environment == 'production')
    name: 🌟 Deploy to Production (Self-hosted)
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 🧹 Clean old containers
        run: |
          echo "🧹 Cleaning old observability-microservice containers..."
          if docker ps -a --format '{{.Names}}' | grep -q '^observability-microservice$'; then
            docker stop 'observability-microservice' && docker rm 'observability-microservice'
          fi
      - name: 🚀 Deploy observability-microservice
        run: |
          set -euo pipefail
          IMAGE_DIGEST="${{ needs.build-image.outputs.image-digest }}"
          IMAGE_NAME_LOWER="${{ needs.build-image.outputs.image-name-lower }}"
          FULL_IMAGE="ghcr.io/${IMAGE_NAME_LOWER}@${IMAGE_DIGEST}"
          docker login ghcr.io -u ${{ github.actor }} --password-stdin <<< '${{ secrets.GITHUB_TOKEN }}'
          docker pull "${FULL_IMAGE}"
          docker network create conexao-network 2>/dev/null || true
          docker run -d \
            --name "observability-microservice" \
            --network conexao-network \
            --restart unless-stopped \
            -p "8085:8085" \
            --health-cmd="curl -f http://localhost:8085/actuator/health/readiness || exit 1" \
            --health-interval=30s \
            --health-timeout=10s \
            --health-retries=5 \
            --health-start-period=60s \
            -e SPRING_PROFILES_ACTIVE="prod,azure" \
            -e SERVER_PORT="8085" \
            -e TZ="America/Sao_Paulo" \
            -e AZURE_CLIENT_ID='${{ secrets.AZURE_CLIENT_ID }}' \
            -e AZURE_TENANT_ID='${{ secrets.AZURE_TENANT_ID }}' \
            -e AZURE_SUBSCRIPTION_ID='${{ secrets.AZURE_SUBSCRIPTION_ID }}' \
            -e AZURE_KEYVAULT_ENDPOINT='${{ secrets.AZURE_KEYVAULT_ENDPOINT }}' \
            -e AZURE_KEYVAULT_NAME='${{ secrets.AZURE_KEYVAULT_NAME }}' \
            --label "traefik.enable=true" \
            --label "traefik.docker.network=conexao-network" \
            --label "traefik.http.routers.observability.rule=Host(\\`observability.conexaodesorte.com.br\\`)" \
            --label "traefik.http.routers.observability.entrypoints=websecure" \
            --label "traefik.http.routers.observability.tls.certresolver=letsencrypt" \
            --label "traefik.http.services.observability.loadbalancer.server.port=8085" \
            "${FULL_IMAGE}"
      - name: Wait for service to be ready
        run: |
          TIMEOUT=180
          ELAPSED=0
          while [ $ELAPSED -lt $TIMEOUT ]; do
            if docker exec observability-microservice curl -f -s http://localhost:8085/actuator/health/readiness >/dev/null 2>&1; then
              echo "✅ Service is ready and healthy!"
              exit 0
            fi
            sleep 10
            ELAPSED=$((ELAPSED + 10))
          done
          echo "❌ Service failed to become ready"
          docker logs observability-microservice
          exit 1

  notify:
    runs-on: self-hosted
    name: 📢 Notification
    if: always()
    needs: [build-and-test, build-image, sign-image, deploy-production]
    steps:
      - name: 📧 Send Slack notification
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ "${{ needs.deploy-production.result }}" = "success" ]; then
            STATUS="🎉 SUCCESS"
            COLOR="good"
          else
            STATUS="❌ FAILED"
            COLOR="danger"
          fi
          if [ -n "${SLACK_WEBHOOK_URL}" ]; then
            curl -X POST -H 'Content-type: application/json' \
            --data "{'text':'$STATUS: Observability Microservice Deployment','attachments':[{'color':'$COLOR','fields':[{'title':'Branch','value':'${{ github.ref_name }}','short':true},{'title':'Commit','value':'${{ github.sha }}','short':true}]}]}" \
            $SLACK_WEBHOOK_URL
